openapi: 3.0.3

info:
  title: Islamic Network - Prayer Times API
  version: 1.0.0
  description:
    $ref: description.md

tags:
  - name: Prayer Times Methods

servers:
  - url: 'https'

paths:
  /v1/methods:
    $ref: api/prayer-times-methods/definition.yaml
